- README.md
- Add ToC
- Add badges
- Fix old links
> Feat: minor update on README.md

- README.md
- node/src/chain_spec.rs
- node/src/command.rs
- Change `UNIT` default token to `VArch` token
> Varch token

- .github/workflows/build.yml
This PR adds the github actions workflow for checks.
> Added github workflow for CI

- node/build.rs
- node/src/chain_spec.rs
- node/src/cli.rs
- node/src/command.rs
- node/src/main.rs
- node/src/rpc.rs
- node/src/service.rs
- pallets/template/src/benchmarking.rs
- pallets/template/src/lib.rs
- pallets/template/src/mock.rs
- pallets/template/src/tests.rs
- runtime/build.rs
- runtime/src/lib.rs
This PR formats everything according to rustfmt.
> Formatting cleanup

- node/src/rpc.rs
- node/src/service.rs
- pallets/template/src/lib.rs
> Clean up for CI

- Cargo.lock
- runtime/Cargo.toml
- runtime/src/lib.rs
- Add IPS pallet to InvArch-node from library
> Feat: add IPS pallet

- Cargo.lock
- runtime/Cargo.toml
- runtime/src/lib.rs
- import ipt, ips, ipo pallets with prefix
> Update: import pallet with prefix

- Cargo.lock
- runtime/Cargo.toml
- runtime/src/lib.rs
> Feat: Add DEV pallet after refactoring

- Cargo.lock
- runtime/Cargo.toml
- Update dependencies to InvArch EVM in runtime cargo
> Update dependencies to InvArch EVM

- Cargo.lock
- runtime/Cargo.toml
- runtime/src/lib.rs
> Feat: update dependencies in runtime lib

- node/Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
This PR upgrades Substrate to polkadot-v0.9.15 and changes IPT to IPF in preparation for the changes in the pallet library
> Upgrade substrate to polkadot-v0.9.15 and change IPT to IPF

- Cargo.lock
- node/Cargo.toml
- node/src/chain_spec.rs
- node/src/cli.rs
- node/src/command.rs
- node/src/service.rs
- runtime/Cargo.toml
- runtime/src/constants.rs
- runtime/src/lib.rs
- This upgrade to Polkadot-v0.9.16 is working in progress. Would be great if @arrudagates could take a look into it.
> Upgrade to Polkadot-v0.9.16

- runtime/Cargo.toml
- runtime/src/lib.rs
This PR adds the SmartIP and Multisig pallets to the InvArch node.
> SmartIP and Multisig

- Cargo.lock
- node/Cargo.toml
- node/src/cli.rs
- node/src/command.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
- runtime/src/xcm_config.rs
@arrudagates I'm working to fix it. If there's any chance you have time to check it as well, it'd be much appreciated.
> WIP2: Bump to polkadot-v0.9.17

- runtime/src/lib.rs
This PR introduces in the node the changes intriduced in the pallets by PR https://github.com/InvArch/InvArch-Pallet-Library/pull/117
> Introduce WeightToFeePolynomial type in pallet_ipt

- Cargo.lock
- node/Cargo.toml
- node/src/command.rs
- node/src/service.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
- runtime/src/weights/block_weights.rs
- runtime/src/weights/extrinsic_weights.rs
- runtime/src/weights/mod.rs
- runtime/src/weights/paritydb_weights.rs
- runtime/src/weights/rocksdb_weights.rs
- runtime/src/xcm_config.rs
Dependencies
- Frames library https://github.com/InvArch/InvArch-Frames/pull/137
> Bump Polkadot-v0.9.18 WIP

- .gitignore
- Cargo.lock
- runtime/Cargo.toml
- runtime/src/lib.rs
Feature PR for https://github.com/InvArch/InvArch-Frames/pull/141
- Implements IP Licenses for the node
- Modifies the INV4 pallets to work with IPL
Should be draft until tracked PR is merged
> Feat: IP Licenses

- Cargo.lock
- Makefile
- node/Cargo.toml
- node/src/chain_spec.rs
- node/src/command.rs
- node/src/rpc.rs
- node/src/service.rs
Can be started using the Makefile with `make run-solo-alice` and `make run-solo-bob`, or manually with the argument `--chain solo-dev`.
> Solo chain mode using mock validation

- Cargo.lock
- runtime/Cargo.toml
- runtime/src/lib.rs
> Fix benchmark issues with Licenses & Call

- docs/collator-instructions.md
copy of Leemo's GMorDIE collatoooooooor instructions, with my modifications today to use a service user. Now customized for building a collator for tinkernet.
> initial collator instructions

- docs/collator-instructions.md
* add quick instructions to update node (collator and chainspec)
* override existing local copies of collator and chainspec
> collator node update instructions

- runtime/tinkernet/src/lib.rs
This PR bumps spec version to the one currently running in Tinkernet Kusama
> Bump spec version

- Cargo.lock
- runtime/tinkernet/Cargo.toml
- runtime/tinkernet/src/lib.rs
This PR updates the INV4 pallet with the new multisig metadata functionality and bumps the spec for a runtime upgrade.
> INV4 multisig metadata

- res/invarch/invarch-raw.json
Adding dwellir bootnodes into the chainspec
> add dwellir bootnodes

- res/invarch/invarch-raw.json
> Add stake.plus bootnodes

- tinkernet/Cargo.lock
- tinkernet/rust-toolchain.toml
serde@1.0.204 breaks compiles in a lot of nightly releases.
> Fix Tinkernet broken build
